[greeter]
background=/usr/share/backgrounds/ph4ntxm-login.png
logo=/usr/share/backgrounds/ph4ntxm-logo.png
theme-name=Midnight
icon-theme-name=Lyra-blue-dark
font-name=Sans 11
xft-antialias=true
xft-hintstyle=hintfull
xft-rgba=rgb
show-indicators=~language;~session;~power
show-manual-login=false
show-remote-login=false
show-user-image=true
default-user-image=/usr/share/backgrounds/ph4ntxm-logo.png